local others = {}

others.blue_magic = {
    [513] = {id=513, en="Venom Shell",            ja="ベノムシェル", 		duration=  0, element= 5, status= 41},
    [515] = {id=515, en="Maelstrom",              ja="メイルシュトロム",		duration=  0, element= 5, status=  0},
    [517] = {id=517, en="Metallic Body",          ja="メタルボディ",			duration=900, element=15, status= 37},
    [519] = {id=519, en="Screwdriver",            ja="S.ドライバー",		duration=  0, element=15, status=  0},
    [521] = {id=521, en="MP Drainkiss",           ja="MP吸収キッス",		duration=  0, element= 7, status=  0},
    [522] = {id=522, en="Death Ray",              ja="デスレイ",			duration=  0, element= 7, status=  0},
    [524] = {id=524, en="Sandspin",               ja="土竜巻",			duration=  0, element= 3, status=  0},
    [527] = {id=527, en="Smite of Rage",          ja="怒りの一撃",			duration=  0, element=15, status=  0},
    [529] = {id=529, en="Bludgeon",               ja="メッタ打ち",			duration=  0, element=15, status=  0},
    [530] = {id=530, en="Refueling",              ja="リフュエリング",		duration=300, element=15, status= 33},
    [531] = {id=531, en="Ice Break",              ja="アイスブレイク",		duration=  0, element= 1, status=  0},
    [532] = {id=532, en="Blitzstrahl",            ja="B.シュトラール",		duration=  0, element= 4, status=  0},
    [533] = {id=533, en="Self-Destruct",          ja="自爆",				duration=  0, element= 0, status=  0},
    [534] = {id=534, en="Mysterious Light",       ja="神秘の光",			duration=  0, element= 2, status=  0},
    [535] = {id=535, en="Cold Wave",              ja="コールドウェーブ",		duration=  0, element= 1, status=  0},
    [536] = {id=536, en="Poison Breath",          ja="ポイズンブレス",		duration=  0, element= 5, status=  0},
    [537] = {id=537, en="Stinking Gas",           ja="スティンキングガス",     duration=  0, element= 2, status=  0},
    [538] = {id=538, en="Memento Mori",           ja="メメントモーリ",		duration= 60, element=15, status=190},
    [539] = {id=539, en="Terror Touch",           ja="テラータッチ",			duration=  0, element=15, status=  0},
    [540] = {id=540, en="Spinal Cleave",          ja="スパイナルクリーブ",		duration=  0, element=15, status=  0},
    [541] = {id=541, en="Blood Saber",            ja="ブラッドセイバー",		duration=  0, element= 7, status=  0},
    [542] = {id=542, en="Digest",                 ja="消化",				duration=  0, element= 7, status=  0},
    [543] = {id=543, en="Mandibular Bite",        ja="M.バイト",			duration=  0, element=15, status=  0},
    [544] = {id=544, en="Cursed Sphere",          ja="カースドスフィア",		duration=  0, element= 5, status=  0},
    [545] = {id=545, en="Sickle Slash",           ja="シックルスラッシュ",     duration=  0, element=15, status=  0},
    [547] = {id=547, en="Cocoon",                 ja="コクーン",			duration= 90, element=15, status= 93},
    [548] = {id=548, en="Filamented Hold",        ja="F.ホールド", 		duration=  0, element= 3, status=  0},
    [549] = {id=549, en="Pollen",                 ja="花粉",				duration=  0, element=15, status=  0},
    [551] = {id=551, en="Power Attack",           ja="パワーアタック",		duration=  0, element=15, status=  0},
    [554] = {id=554, en="Death Scissors",         ja="デスシザース",			duration=  0, element=15, status=  0},
    [555] = {id=555, en="Magnetite Cloud",        ja="磁鉄粉",			duration=  0, element= 3, status=  0},
    [557] = {id=557, en="Eyes On Me",             ja="アイズオンミー",		duration=  0, element= 7, status=  0},
    [560] = {id=560, en="Frenetic Rip",           ja="F.リップ",			duration=  0, element=15, status=  0},
    [561] = {id=561, en="Frightful Roar",         ja="フライトフルロア",		duration=  0, element= 2, status=  0},
    [563] = {id=563, en="Hecatomb Wave",          ja="ヘカトンウェーブ",		duration=  0, element= 2, status=  0},
    [564] = {id=564, en="Body Slam",              ja="ボディプレス",			duration=  0, element=15, status=  0},
    [565] = {id=565, en="Radiant Breath",         ja="R.ブレス",			duration=  0, element= 6, status=  0},
    [567] = {id=567, en="Helldive",               ja="ヘルダイブ",			duration=  0, element=15, status=  0},
    [569] = {id=569, en="Jet Stream",             ja="ジェットストリーム",		duration=  0, element=15, status=  0},
    [570] = {id=570, en="Blood Drain",            ja="吸血",				duration=  0, element= 7, status=  0},
    [572] = {id=572, en="Sound Blast",            ja="サウンドブラスト",		duration=  0, element= 0, status=  0},
    [573] = {id=573, en="Feather Tickle",         ja="フェザーティックル",		duration=  0, element= 2, status=  0},
    [574] = {id=574, en="Feather Barrier",        ja="フェザーバリア",		duration= 30, element=15, status= 92},
    [575] = {id=575, en="Jettatura",              ja="ジェタチュラ",			duration=  0, element= 7, status=  0},
    [576] = {id=576, en="Yawn",                   ja="ヤーン",				duration= 90, element= 6, status=  2},
    [577] = {id=577, en="Foot Kick",              ja="フットキック",			duration=  0, element=15, status=  0},
    [578] = {id=578, en="Wild Carrot",            ja="ワイルドカロット",		duration=  0, element=15, status=  0},
    [579] = {id=579, en="Voracious Trunk",        ja="吸印",				duration=  0, element= 2, status=  0},
    [581] = {id=581, en="Healing Breeze",         ja="いやしの風",			duration=  0, element=15, status=  0},
    [582] = {id=582, en="Chaotic Eye",            ja="カオティックアイ",		duration=  0, element= 2, status=  0},
    [584] = {id=584, en="Sheep Song",             ja="シープソング",			duration= 60, element= 6, status=  2},
    [585] = {id=585, en="Ram Charge",             ja="ラムチャージ",			duration=  0, element=15, status=  0},
    [587] = {id=587, en="Claw Cyclone",           ja="クローサイクロン",		duration=  0, element=15, status=  0},
    [588] = {id=588, en="Lowing",                 ja="ロウイン",			duration=  0, element= 0, status=  0},
    [589] = {id=589, en="Dimensional Death",      ja="次元殺",			duration=  0, element=15, status=  0},
    [591] = {id=591, en="Heat Breath",            ja="火炎の息",			duration=  0, element= 0, status=  0},
    [592] = {id=592, en="Blank Gaze",             ja="ブランクゲイズ",		duration=  0, element= 6, status=  0},
    [593] = {id=593, en="Magic Fruit",            ja="マジックフルーツ",		duration=  0, element=15, status=  0},
    [594] = {id=594, en="Uppercut",               ja="アッパーカット",		duration=  0, element=15, status=  0},
    [595] = {id=595, en="1000 Needles",           ja="針千本",			duration=  0, element= 6, status=  0},
    [596] = {id=596, en="Pinecone Bomb",          ja="まつぼっくり爆弾",		duration=  0, element=15, status=  0},
    [597] = {id=597, en="Sprout Smack",           ja="スプラウトスマック",     duration=  0, element=15, status=  0},
    [598] = {id=598, en="Soporific",              ja="サペリフィック",		duration=  0, element= 7, status=  0},
    [599] = {id=599, en="Queasyshroom",           ja="マヨイタケ",			duration=  0, element=15, status=  0},
    [603] = {id=603, en="Wild Oats",              ja="種まき",			duration=  0, element=15, status=  0},
    [604] = {id=604, en="Bad Breath",             ja="臭い息",			duration=  0, element= 3, status=  0},
    [605] = {id=605, en="Geist Wall",             ja="ガイストウォール",		duration=  0, element= 7, status=  0},
    [606] = {id=606, en="Awful Eye",              ja="アーフルアイ",			duration=  0, element= 5, status=  0},
    [608] = {id=608, en="Frost Breath",           ja="フロストブレス",		duration=  0, element= 1, status=  0},
    [610] = {id=610, en="Infrasonics",            ja="超低周波",			duration=  0, element= 1, status=  0},
    [611] = {id=611, en="Disseverment",           ja="ディセバーメント",		duration=  0, element=15, status=  0},
    [612] = {id=612, en="Actinic Burst",          ja="A.バースト",			duration=  0, element= 6, status=  0},
    [613] = {id=613, en="Reactor Cool",           ja="反応炉冷却",		duration=180, element=15, status= 93},
    [614] = {id=614, en="Saline Coat",            ja="セイリーンコート",		duration=120, element=15, status=191},
    [615] = {id=615, en="Plasma Charge",          ja="プラズマチャージ",		duration=750, element=15, status= 38},
    [616] = {id=616, en="Temporal Shift",         ja="テンポラルシフト",		duration=  0, element= 4, status=  0},
    [617] = {id=617, en="Vertical Cleave",        ja="バーチカルクリーヴ",     duration=  0, element=15, status=  0},
    [618] = {id=618, en="Blastbomb",              ja="炸裂弾",			duration=  0, element= 0, status=  0},
    [620] = {id=620, en="Battle Dance",           ja="バトルダンス",			duration=  0, element=15, status=  0},
    [621] = {id=621, en="Sandspray",              ja="サンドスプレー",		duration=  0, element= 7, status=  0},
    [622] = {id=622, en="Grand Slam",             ja="グランドスラム",		duration=  0, element=15, status=  0},
    [623] = {id=623, en="Head Butt",              ja="ヘッドバット",			duration=  0, element=15, status=  0},
    [626] = {id=626, en="Bomb Toss",              ja="爆弾投げ",			duration=  0, element= 0, status=  0},
    [628] = {id=628, en="Frypan",                 ja="フライパン",			duration=  0, element=15, status=  0},
    [629] = {id=629, en="Flying Hip Press",       ja="F.ヒッププレス",		duration=  0, element= 2, status=  0},
    [631] = {id=631, en="Hydro Shot",             ja="ハイドロショット",		duration=  0, element=15, status=  0},
    [632] = {id=632, en="Diamondhide",            ja="金剛身",			duration= 90, element=15, status= 37},
    [633] = {id=633, en="Enervation",             ja="吶喊",				duration=  0, element= 7, status=  0},
    [634] = {id=634, en="Light of Penance",       ja="贖罪の光",			duration=  0, element= 6, status=  0},
    [636] = {id=636, en="Warm-Up",                ja="ワームアップ", 		duration=180, element=15, status=  0},
    [637] = {id=637, en="Firespit",               ja="ファイアースピット",		duration=  0, element= 0, status=  0},
    [638] = {id=638, en="Feather Storm",          ja="羽根吹雪",			duration=  0, element=15, status=  0},
    [640] = {id=640, en="Tail Slap",              ja="テールスラップ",		duration=  0, element=15, status=  0},
    [641] = {id=641, en="Hysteric Barrage",       ja="H.バラージ",			duration=  0, element=15, status= 73},
    [642] = {id=642, en="Amplification",          ja="ねたみ種",			duration= 90, element=15, status=  0},
    [643] = {id=643, en="Cannonball",             ja="キャノンボール",		duration=  0, element=15, status=  0},
    [644] = {id=644, en="Mind Blast",             ja="マインドブラスト",		duration=  0, element= 4, status=  0},
    [645] = {id=645, en="Exuviation",             ja="イグジュビエーション",	duration=  0, element= 0, status=  0},
    [646] = {id=646, en="Magic Hammer",           ja="マジックハンマー",		duration=  0, element= 6, status=  0},
    [647] = {id=647, en="Zephyr Mantle",          ja="ゼファーマント",		duration=900, element= 2, status= 36},
    [648] = {id=648, en="Regurgitation",          ja="リガージテーション",		duration=  0, element= 5, status=  0},
    [650] = {id=650, en="Seedspray",              ja="シードスプレー",		duration=  0, element= 3, status=  0},
    [651] = {id=651, en="Corrosive Ooze",         ja="コローシブウーズ",		duration=  0, element= 5, status=  0},
    [652] = {id=652, en="Spiral Spin",            ja="スパイラルスピン",		duration=  0, element=15, status=  0},
    [653] = {id=653, en="Asuran Claws",           ja="アシュラクロー",		duration=  0, element=15, status=  0},
    [654] = {id=654, en="Sub-zero Smash",         ja="サブゼロスマッシュ",     duration=  0, element=15, status=  0},
    [655] = {id=655, en="Triumphant Roar",        ja="共鳴",				duration= 90, element= 0, status= 91},
    [656] = {id=656, en="Acrid Stream",           ja="アクリッドストリーム",	duration=  0, element= 5, status=  0},
    [657] = {id=657, en="Blazing Bound",          ja="ブレーズバウンド",		duration=  0, element= 0, status=  0},
    [658] = {id=658, en="Plenilune Embrace",      ja="P.エンブレイス",		duration=  0, element= 6, status=  0},
    [659] = {id=659, en="Demoralizing Roar",      ja="D.ロア",			duration=  0, element= 5, status=  0},
    [660] = {id=660, en="Cimicine Discharge",     ja="C.ディスチャージ",		duration=  0, element= 3, status=  0},
    [661] = {id=661, en="Animating Wail",         ja="鯨波",				duration=300, element= 2, status= 33},
    [662] = {id=662, en="Battery Charge",         ja="バッテリーチャージ",		duration=300, element= 6, status= 43},
    [663] = {id=663, en="Leafstorm",              ja="リーフストーム",		duration=  0, element= 2, status=  0},
    [664] = {id=664, en="Regeneration",           ja="リジェネレーション",		duration= 90, element= 6, status= 42},
    [665] = {id=665, en="Final Sting",            ja="ファイナルスピア",		duration=  0, element=15, status=  0},
    [666] = {id=666, en="Goblin Rush",            ja="ゴブリンラッシュ",		duration=  0, element=15, status=  0},
    [667] = {id=667, en="Vanity Dive",            ja="バニティダイブ",		duration=  0, element=15, status=  0},
    [668] = {id=668, en="Magic Barrier",          ja="マジックバリア",		duration=900, element= 7, status=152},
    [669] = {id=669, en="Whirl of Rage",          ja="怒りの旋風",			duration=  0, element=15, status=  0},
    [670] = {id=670, en="Benthic Typhoon",        ja="ベンシクタイフーン",		duration=  0, element=15, status=  0},
    [671] = {id=671, en="Auroral Drape",          ja="オーロラルドレープ",		duration=  0, element= 2, status=  0},
    [672] = {id=672, en="Osmosis",                ja="オスモーシス",			duration=  0, element= 7, status=  0},
    [673] = {id=673, en="Quad. Continuum",        ja="四連突",			duration=  0, element=15, status=  0},
    [674] = {id=674, en="Fantod",                 ja="ファンタッド",			duration=180, element= 0, status= 45},
    [675] = {id=675, en="Thermal Pulse",          ja="サーマルパルス",		duration=  0, element= 0, status=  0},
    [677] = {id=677, en="Empty Thrash",           ja="エンプティスラッシュ",	duration=  0, element=15, status=  0},
    [678] = {id=678, en="Dream Flower",           ja="夢想花",			duration= 90, element= 7, status=  2},
    [679] = {id=679, en="Occultation",            ja="オカルテーション",		duration=300, element= 2, status= 36},
    [680] = {id=680, en="Charged Whisker",        ja="チャージドホイスカー",	duration=  0, element= 4, status=  0},
    [681] = {id=681, en="Winds of Promy.",        ja="虚無の風",			duration=  0, element= 6, status=  0},
    [682] = {id=682, en="Delta Thrust",           ja="デルタスラスト",		duration= 60, element=15, status= 31},
    [683] = {id=683, en="Evryone. Grudge",        ja="みんなの怨み",		duration=  0, element= 7, status=  0},
    [684] = {id=684, en="Reaving Wind",           ja="リービンウィンド",		duration=  0, element= 2, status=  0},
    [685] = {id=685, en="Barrier Tusk",           ja="牙門",				duration=180, element= 3, status=116},
    [686] = {id=686, en="Mortal Ray",             ja="モータルレイ",			duration=  0, element= 7, status=  0},
    [687] = {id=687, en="Water Bomb",             ja="水風船爆弾",		duration= 90, element= 5, status=  6},
    [688] = {id=688, en="Heavy Strike",           ja="重い一撃",			duration=  0, element=15, status=  0},
    [689] = {id=689, en="Dark Orb",               ja="ダークオーブ",			duration=  0, element= 7, status=  0},
    [690] = {id=690, en="White Wind",             ja="ホワイトウィンド",		duration=  0, element= 2, status=  0},
    [692] = {id=692, en="Sudden Lunge",           ja="サドンランジ",			duration=  0, element=15, status=  0},
    [693] = {id=693, en="Quadrastrike",           ja="クアドラストライク",     duration=  0, element=15, status=  0},
    [694] = {id=694, en="Vapor Spray",            ja="ヴェイパースプレー",		duration=  0, element= 5, status=  0},
    [695] = {id=695, en="Thunder Breath",         ja="サンダーブレス",		duration=  0, element= 4, status=  0},
    [696] = {id=696, en="O. Counterstance",       ja="カウンタースタンス",     duration=180, element= 0, status= 61},
    [697] = {id=697, en="Amorphic Spikes",        ja="槍玉",				duration=  0, element=15, status=  0},
    [698] = {id=698, en="Wind Breath",            ja="ウィンドブレス",		duration=  0, element= 2, status=  0},
    [699] = {id=699, en="Barbed Crescent",        ja="偃月刃",			duration=120, element=15, status=146},
    [700] = {id=700, en="Nat. Meditation",        ja="N.メディテイト",		duration= 90, element= 0, status= 91},
    [701] = {id=701, en="Tem. Upheaval",          ja="T.アップヒーヴ",		duration=  0, element= 2, status=  0},
    [702] = {id=702, en="Rending Deluge",         ja="R.デルージュ",		duration=  0, element= 5, status=  0},
    [703] = {id=703, en="Embalming Earth",        ja="エンバームアース",		duration=180, element= 3, status= 13},
    [704] = {id=704, en="Paralyzing Triad",       ja="パラライズトライアド",	duration= 60, element=15, status=  4},
    [705] = {id=705, en="Foul Waters",            ja="ファウルウォーター",		duration=  0, element= 5, status=  0},
    [706] = {id=706, en="Glutinous Dart",         ja="グルーティナスダート",	duration=  0, element=15, status=  0},
    [707] = {id=707, en="Retinal Glare",          ja="レテナグレア",			duration=  0, element= 6, status=  0},
    [708] = {id=708, en="Subduction",             ja="サブダックション",		duration=120, element= 2, status= 12},
    [709] = {id=709, en="Thrashing Assault",      ja="T.アッサルト",		duration=  0, element=15, status=  0},
    [710] = {id=710, en="Erratic Flutter",        ja="エラチックフラッター",		duration=300, element= 2, status= 33},
    [711] = {id=711, en="Restoral",               ja="レストラル",			duration=  0, element= 6, status=  0},
    [712] = {id=712, en="Rail Cannon",            ja="レールキャノン",		duration=  0, element= 6, status=  0},
    [713] = {id=713, en="Diffusion Ray",          ja="ディフュージョンレイ",		duration=  0, element= 6, status=  0},
    [714] = {id=714, en="Sinker Drill",           ja="シンカードリル",		duration=  0, element=15, status=  0},
    [715] = {id=715, en="Molting Plumage",        ja="モルトプルメイジ",		duration=  0, element= 2, status=  0},
    [716] = {id=716, en="Nectarous Deluge",       ja="ネクターデルージュ",     duration=  0, element= 5, status=  0},
    [717] = {id=717, en="Sweeping Gouge",         ja="スイープガウジ",		duration=120, element=15, status=149},
    [718] = {id=718, en="Atra. Libations",        ja="A.ライベーション",		duration=  0, element= 7, status=  0},
    [719] = {id=719, en="Searing Tempest",        ja="シアリングテンペスト",	duration= 60, element= 0, status=128},
    [720] = {id=720, en="Spectral Floe",          ja="スペクトラルフロー",		duration=  0, element= 1, status=  0},
    [721] = {id=721, en="Anvil Lightning",        ja="アンビルライトニング",	duration=  0, element= 4, status=  0},
    [722] = {id=722, en="Entomb",                 ja="エントゥーム",			duration= 60, element= 3, status=  7},
    [723] = {id=723, en="Saurian Slide",          ja="サウリアンスライド",     duration=  0, element=15, status=  0},
    [724] = {id=724, en="Palling Salvo",          ja="ポーリングサルヴォ",     duration=  0, element= 7, status=  0},
    [725] = {id=725, en="Blinding Fulgor",        ja="B.フルゴア",			duration=  0, element= 6, status=  0},
    [726] = {id=726, en="Scouring Spate",         ja="スカウリングスペイト",	duration=  0, element= 5, status=  0},
    [727] = {id=727, en="Silent Storm",           ja="サイレントストーム",     duration=300, element= 2, status=  6},
    [728] = {id=728, en="Tenebral Crush",         ja="テネブラルクラッシュ",	duration=180, element= 7, status=149},
    [736] = {id=736, en="Thunderbolt",            ja="サンダーボルト",		duration=  0, element= 4, status=  0},
    [737] = {id=737, en="Harden Shell",           ja="甲羅強化",			duration= 90, element= 3, status= 93},
    [738] = {id=738, en="Absolute Terror",        ja="アブソルートテラー",		duration=  0, element= 7, status=  0},
    [739] = {id=739, en="Gates of Hades",         ja="ゲーツオブハデス",		duration=  0, element= 0, status=  0},
    [740] = {id=740, en="Tourbillion",            ja="トゥールビヨン",		duration=120, element=15, status=149},
    [741] = {id=741, en="Pyric Bulwark",          ja="ポーラーブルワーク",		duration=300, element= 6, status=150},
    [742] = {id=742, en="Bilgestorm",             ja="ビルジストーム",		duration=  0, element=15, status=  0},
    [743] = {id=743, en="Bloodrake",              ja="ブラッドレイク",		duration=  0, element=15, status=  0},
    [744] = {id=744, en="Droning Whirlwind",      ja="D.ワールウィンド",		duration=  0, element= 2, status=  0},
    [745] = {id=745, en="Carcharian Verve",       ja="カルカリアンヴァーヴ",	duration=  0, element= 5, status= 91},
    [746] = {id=746, en="Blistering Roar",        ja="ブリスターローア",		duration=  0, element= 7, status=  0},
    [747] = {id=747, en="Uproot",                 ja="アップルート",			duration=  0, element= 6, status=  0},
    [748] = {id=748, en="Crashing Thunder",       ja="クラッシュサンダー",     duration=  0, element= 4, status=  0},
    [749] = {id=749, en="Polar Roar",             ja="ポラーロア",			duration=  0, element= 1, status=  0},
    [750] = {id=750, en="Mighty Guard",           ja="マイティガード",		duration=180, element= 6, status=604},
    [751] = {id=751, en="Cruel Joke",             ja="クルエルジョーク",		duration= 60, element= 7, status= 15},
    [752] = {id=752, en="Cesspool",               ja="セスプール",			duration=  0, element= 5, status=  0},
    [753] = {id=753, en="Tearing Gust",           ja="テーリングガスト",		duration=  0, element= 2, status=  0},
}

return others